///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  // Singleton instance
  static final Assets instance = Assets._();

  // Factory constructor to return the same instance
  factory Assets() {
    return instance;
  }
  String fontsAbeze = 'AbzeRegular';
  String imagesBackground = 'assets/images/background.svg';
  String imagesBackgroundshape = 'assets/images/backgroundshape.png';
  String imagesLogo = 'assets/images/logo.png';
  String imagesBack2 = 'assets/images/back2.svg';
  String imagesMenu = 'assets/images/menu.svg';
  String imagesQuantity = 'assets/images/quantity.svg';
  String imagesCalender = 'assets/images/calender.png';
  String imagesBottle = 'assets/images/bottle.png';
  String imagesGraph = 'assets/images/graph.png';
  String imagesBack = 'assets/images/back.svg';
  String imagesEditicon = 'assets/images/editicon.svg';
   String imagesPaymentcollection = 'assets/images/paymentcollection.svg';
   String imagesPendingdelivery = 'assets/images/pendingdelivery.svg';
   String imagesCompletedelivety = 'assets/images/completedelivety.svg';
   String assetsImagesBottle = 'assets/images/bottle.svg';
  String imagesImgBack = 'assets/images/img_back.jpeg';
  String imagesCall = 'assets/images/call.svg';

  String calender = 'assets/images/calender.svg';
  String address = 'assets/images/address.svg';
  String phone = 'assets/images/phone.svg';
  String user = 'assets/images/user.svg';
  String email = 'assets/images/email.svg';
  String password = 'assets/images/password.svg';
  String whatsapp = 'assets/images/whatsapp.svg';
  String telegram = 'assets/images/telegram.svg';
  String adImage = 'assets/images/adimg.png';

}
